version: "3.3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mariadb/data:/var/lib/mysql
      - ${PWD}/mariadb/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: new1234
      TZ: Asia/Seoul
