pipeline {
	
	agent any

	stages {
        stage('========== Clone repository ==========') {
            steps {
				sh "echo [build] START"
				sh "pwd"
				sh "echo [bulid] END"
			}
        }

        stage("dockerize") {
            steps {
                script {
                    echo "[dockerize] START" 
                    docker.withRegistry('https://registry.hub.docker.com', '42bba9ad-eefc-402d-a108-1148fdd417bd') {
                        def containerCurrentImage = docker.build("chansubchoi/test1", "-f Dockerfile")
                        containerCurrentImage.push()
                    }
                    echo "[dockerize] END" 
                }
            }
        }

    }
}

